### ISSUE TITLE
Для ссылок добавить классы

### ISSUE THREAD

**Issue by igosheva** [semperhomolupus/semperhomolupus.github.io#10]
https://github.com/semperhomolupus/semperhomolupus.github.io/blob/98a48d05d9aeeeedce935962975a3729fa71707d/loft-first/services.html#L132

**Comment by igosheva** [comment]
Маржины лучше вынести для footer-socials__item , так как отталкиваться друг от друга элементы должны отталкиваться не за счет отступов у внутренних элементов, а за счет своих собственных внешних отступов.

**Comment by igosheva** [comment]
И background отдельно пропиши свойства.

**Comment by semperhomolupus** [comment]
done
