### ISSUE TITLE
Лучше везде для line-height используй относительные единицы, например в данном случае 1.5. Схема расчета line-height равно font-size*значение

### ISSUE THREAD

**Issue by igosheva** [semperhomolupus/semperhomolupus.github.io#12]
https://github.com/semperhomolupus/semperhomolupus.github.io/blob/689b54b4b2992dabf47daebde8d6b5b7912d3a3d/loft-first/css/style.css#L86

**Comment by semperhomolupus** [comment]
done, проверил все и переделал, но использовал 1.42
