### ISSUE TITLE
Внешние отступы лучше передавать родителю, у детей кое-где они могут не сработать

### ISSUE THREAD

**Issue by igosheva** [semperhomolupus/semperhomolupus.github.io#13]
https://github.com/semperhomolupus/semperhomolupus.github.io/blob/689b54b4b2992dabf47daebde8d6b5b7912d3a3d/loft-first/css/style.css#L320

**Comment by igosheva** [comment]
footer-socials__title - тоже самое замечание

**Comment by semperhomolupus** [comment]
done
