### ISSUE TITLE
Ошибка в нейминге: больше 2 слов в именовании класса не делаем

### ISSUE THREAD

**Issue by igosheva** [semperhomolupus/semperhomolupus.github.io#14]
https://github.com/semperhomolupus/semperhomolupus.github.io/blob/689b54b4b2992dabf47daebde8d6b5b7912d3a3d/loft-first/services.html#L48

**Comment by igosheva** [comment]
Т.е. должно быть не main__breadcrumbs-item-link, а main__breadcrumbs-link

**Comment by semperhomolupus** [comment]
done
