### ISSUE TITLE
Лишнее свойство

### ISSUE THREAD

**Issue by igosheva** [semperhomolupus/semperhomolupus.github.io#19]
https://github.com/semperhomolupus/semperhomolupus.github.io/blob/689b54b4b2992dabf47daebde8d6b5b7912d3a3d/loft-first/css/style.css#L621

**Comment by semperhomolupus** [comment]
исправил, пришлось немного переверстать, стало лучше
раньше это было запасное свойство на случай, если у отзыва очень маленькое описание, подошел к проблеме более универсально
