### ISSUE TITLE
Оттолкнуть от верха за счет margin-top

### ISSUE THREAD

**Issue by igosheva** [semperhomolupus/semperhomolupus.github.io#2]
https://github.com/semperhomolupus/semperhomolupus.github.io/blob/98a48d05d9aeeeedce935962975a3729fa71707d/loft-first/services.html#L16

**Comment by igosheva** [comment]
Когда ты прописываешь элементы padding, он входит в общую высоту и ширину элемента. Соответственно в данном случае за счет паддингов верх и низ от логотипа стали также кликабельными, а этого не должно быть.

**Comment by semperhomolupus** [comment]
done
