### ISSUE TITLE
Сделать все паддинги одинаковыми по 10px

### ISSUE THREAD

**Issue by igosheva** [semperhomolupus/semperhomolupus.github.io#26]
https://github.com/semperhomolupus/semperhomolupus.github.io/blob/689b54b4b2992dabf47daebde8d6b5b7912d3a3d/loft-first/css/style.css#L768

**Comment by igosheva** [comment]
Ну и что, что не по пиксель перфекту, так будет правильнее

**Comment by semperhomolupus** [comment]
done
