### ISSUE TITLE
Убрать фиксированную высоту у элемента

### ISSUE THREAD

**Issue by igosheva** [semperhomolupus/semperhomolupus.github.io#3]
https://github.com/semperhomolupus/semperhomolupus.github.io/blob/98a48d05d9aeeeedce935962975a3729fa71707d/loft-first/services.html#L23

**Comment by igosheva** [comment]
Если ты добавишь внутри этого элемента еще одну строку, то она выпадет из элемента. На созвоне я говорила, что задавать фиксированную высоту нужно в крайнем случае когда это действительно необходимо. В остальных случаях необходимой высоты можно добиться за счет внутреннего контента

**Comment by semperhomolupus** [comment]
done
