### ISSUE TITLE
Ширина карточки

### ISSUE THREAD

**Issue by igosheva** [semperhomolupus/semperhomolupus.github.io#8]
https://github.com/semperhomolupus/semperhomolupus.github.io/blob/98a48d05d9aeeeedce935962975a3729fa71707d/loft-first/services.html#L46

**Comment by igosheva** [comment]
Для каждой li сделать максимальную ширину больше ( max-width: 260px; ), но уменьшить маржин справа. Потому что так получается, что у тебя внутренний текст (main-service__text) шире, чем сама карточка, а это грубая ошибка. Когда задашь ширину для li больше можно будет вообще убрать ширину у main-service__text

**Comment by semperhomolupus** [comment]
done
